### ISSUE TITLE
feature request : Ignore invalid certificate while posting to SQSD_HTTP_URL

### ISSUE THREAD

**Issue by julienbornstein** [fterrag/simple-sqsd#9]
Hello, 
When posting to a local https with generated localhost certificate it could be useful to  allow invalid certificate and by pass security check using `InsecureSkipVerify`.
This could be setup with an Environnement var like `SQSD_SSL_ENABLED=false/true` (default true)

**Comment by fterrag** [comment]
Addressed in #11
